#ifndef StVecMesonEpdMaker_h
#define StVecMesonEpdMaker_h

#include "StMaker.h"
#include "TString.h"

class StPicoDst;
class StPicoDstMaker;
class StPicoEvent;
class StRefMultCorr;
//class StRunIdEventsDb;
class StCombPID;
class StVecMesonEpdCut;
class StVecMesonEpdProManger;
class StVecMesonEpdCorrection;
class StVecMesonEpdHistoManger;
class StVecMesonEpdTree;
class StUtility;

class StEventPlaneHistoManager;
class StEventPlaneProManager;
class StEpdEpManager;

class StEpdEpFinder;
class StEpdEpInfo;
class StEpdGeom;

class StVecMesonEpdMaker : public StMaker {
  public:
    StVecMesonEpdMaker(const char *name, StPicoDstMaker *picoMaker, const char *jobCounter, const Int_t Mode, const Int_t Energy, const Int_t Flag_ME, const Int_t Flag_PID);
    virtual ~StVecMesonEpdMaker();
    
    virtual Int_t Init();
    virtual Int_t Make();
    virtual void  Clear(Option_t *opt="");
    virtual Int_t Finish();
    
  private:
    StPicoDstMaker *mPicoDstMaker;
    StPicoDst      *mPicoDst;
    StPicoEvent *mPicoEvent;
    static StRefMultCorr *mRefMultCorr;
    StUtility *mUtility;
    //StRunIdEventsDb *mRunIdEventsDb;
    StVecMesonEpdCut *mVecMesonCut;
    StVecMesonEpdProManger *mVecMesonProManger;
    StVecMesonEpdCorrection *mVecMesonCorrection;
    StVecMesonEpdHistoManger *mVecMesonHistoManger;
    StVecMesonEpdTree *mVecMesonTree;

    StEventPlaneHistoManager *mEventPlaneHistoManager;
    StEventPlaneProManager *mEventPlaneProManager;

    StEpdEpFinder *mEpFinder;
    StEpdEpManager *mEpdEpManager;
    
    TClonesArray *mEpdHits;
    TClonesArray *mTracks;
    TClonesArray *mEventClonesArray;

    StEpdGeom *mEpdGeom;

    Int_t mMode;
    Int_t mEnergy;
    Int_t mFlag_ME;
    Int_t mFlag_PID;
 
    std::string mName_PID[3] = {"Phi","Rho","KStar"};

    TString mInPut_Corr_ReCenter;

    TString mOutPut_ReCenterPar;
    TString mOutPut_ShiftPar;
    TString mOutPut_Resolution;
    TString mOutPut_PID;

    TFile *mFile_ReCenterPar;
    TFile *mFile_ShiftPar;
    TFile *mFile_Resolution;
    TFile *mFile_PID;

    string mOutPut_EpdResults;
    string mInPut_EpdCorrections;
    string mOutPut_EpdCorrections; // output will be autogenerated by StEpdEpFinder

    TFile *mFile_EpdResults;

    Int_t mUsedTrackCounter;

    ClassDef(StVecMesonEpdMaker, 1)
};

#endif
