#!/bin/bash

#root -l -b -q calSysErrorPhiY.C\(4,0,\"Raw\",0,0,\"eta1_eta1\"\)
#root -l -b -q calSysErrorPhiY.C\(4,0,\"AccRes\",0,0,\"eta1_eta1\"\)
#root -l -b -q calSysErrorPhiY.C\(4,0,\"AccRes\",0,0,\"eta1_eta1\"\)

#root -l -b -q calSysErrorPhiY_AfterIntegration.C\(4,0,\"AccRes\",0,0,0,\"eta0p4\"\)
#root -l -b -q calSysErrorPhiY_AfterIntegration.C\(4,0,\"AccRes\",0,0,0,\"eta0p6\"\)
#root -l -b -q calSysErrorPhiY_AfterIntegration.C\(4,0,\"AccRes\",0,0,0,\"eta0p8\"\)
#root -l -b -q calSysErrorPhiY_AfterIntegration.C\(4,0,\"AccRes\",0,0,0,\"eta1_eta1\"\)

#root -l -b -q calSysErrorPhiY_AfterIntegration.C\(4,0,\"AccRes\",0,0,0,\"eta0p4\"\)
#root -l -b -q calSysErrorPhiY_AfterIntegration.C\(4,0,\"AccRes\",0,0,0,\"eta0p6\"\)
#root -l -b -q calSysErrorPhiY_AfterIntegration.C\(4,0,\"AccRes\",0,0,0,\"eta0p8\"\)
#root -l -b -q calSysErrorPhiY_AfterIntegration.C\(4,0,\"AccRes\",0,0,0,\"eta1_eta1\"\)
#
#root -l -b -q calSysErrorPhiY_AfterIntegration.C\(4,0,\"Raw\",0,0,0,\"eta0p4\"\)
#root -l -b -q calSysErrorPhiY_AfterIntegration.C\(4,0,\"Raw\",0,0,0,\"eta0p6\"\)
#root -l -b -q calSysErrorPhiY_AfterIntegration.C\(4,0,\"Raw\",0,0,0,\"eta0p8\"\)
#root -l -b -q calSysErrorPhiY_AfterIntegration.C\(4,0,\"Raw\",0,0,0,\"eta1_eta1\"\)

#root -l -b -q calSysErrorPhiCent.C\(4,0,\"Raw\",0,0,\"eta0p4\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"Raw\",0,0,\"eta0p6\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"Raw\",0,0,\"eta0p8\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"Raw\",0,0,\"eta1_eta1\"\)

#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,2,\"eta0p4\",\"fixed_ptbin/EffAcc\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,2,\"eta0p6\",\"fixed_ptbin/EffAcc\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,2,\"eta0p8\",\"fixed_ptbin/EffAcc\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"fixed_ptbin/EffAcc\"\)

#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,2,\"eta0p4\",\"FixedSimRes\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,2,\"eta0p6\",\"FixedSimRes\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,2,\"eta0p8\",\"FixedSimRes\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"FixedResolutionFinal\"\)
#root -l -b -q calSysErrorPhiCent_FixedSys.C\(3,0,\"Raw\",0,0,1,\"eta1_eta1\",\"\"\)
#root -l -b -q calSysErrorPhiCent_FixedSys.C\(3,0,\"Raw\",0,0,2,\"eta1_eta1\",\"\"\)
#root -l -b -q calSysErrorPhiCent_FixedSys.C\(4,0,\"Raw\",0,0,1,\"eta1_eta1\",\"\"\)
#root -l -b -q calSysErrorPhiCent_FixedSys.C\(4,0,\"Raw\",0,0,2,\"eta1_eta1\",\"\"\)
#root -l -b -q calSysErrorPhiCent_FixedSys_RawRes.C\(3,0,\"Raw\",0,0,1,\"eta1_eta1\",\"\"\)
#root -l -b -q calSysErrorPhiCent_FixedSys_RawRes.C\(3,0,\"Raw\",0,0,2,\"eta1_eta1\",\"\"\)
#root -l -b -q calSysErrorPhiCent_FixedSys_RawRes.C\(4,0,\"Raw\",0,0,1,\"eta1_eta1\",\"\"\)
#root -l -b -q calSysErrorPhiCent_FixedSys_RawRes.C\(4,0,\"Raw\",0,0,2,\"eta1_eta1\",\"\"\)
#root -l -b -q calSysErrorPhiCent_FixedSys.C\(3,0,\"AccRes\",0,0,1,\"eta1_eta1\",\"\"\)
#root -l -b -q calSysErrorPhiCent_FixedSys.C\(3,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"\"\)
#root -l -b -q calSysErrorPhiCent_FixedSys.C\(4,0,\"AccRes\",0,0,1,\"eta1_eta1\",\"\"\)
#root -l -b -q calSysErrorPhiCent_FixedSys.C\(4,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"FixedResolutionFinal\"\)
#root -l -b -q calSysErrorPhiCent.C\(3,0,\"Raw\",0,0,1,\"eta0p4\",\"\"\)
#root -l -b -q calSysErrorPhiCent.C\(3,0,\"Raw\",0,0,1,\"eta0p6\",\"\"\)
#root -l -b -q calSysErrorPhiCent.C\(3,0,\"Raw\",0,0,1,\"eta0p8\",\"\"\)
#root -l -b -q calSysErrorPhiCent.C\(3,0,\"Raw\",0,0,1,\"eta1_eta1\",\"\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,1,\"eta0p4\",\"\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,1,\"eta0p6\",\"\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,1,\"eta0p8\",\"\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,1,\"eta1_eta1\",\"\"\)

#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,2,\"eta0p4\",\"FixedSimRes\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,2,\"eta0p6\",\"FixedSimRes\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,2,\"eta0p8\",\"FixedSimRes\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"FixedSimRes\"\)

#root -l -b -q calSysErrorPhiCent.C\(4,0,\"Raw\",0,0,2,\"eta0p4\",\"\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"Raw\",0,0,2,\"eta0p6\",\"\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"Raw\",0,0,2,\"eta0p8\",\"\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"Raw\",0,0,2,\"eta1_eta1\",\"\"\)

#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,\"eta0p4\",\"_sub\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,\"eta0p6\",\"_sub\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,\"eta0p8\",\"_sub\"\)
#root -l -b -q calSysErrorPhiCent.C\(4,0,\"AccRes\",0,0,\"eta1_eta1\",\"_sub\"\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(3,0,\"AccRes\",0,0,1,\"eta1_eta1\",\"Poly\"\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(3,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"Poly\"\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"AccRes\",0,0,1,\"eta1_eta1\",\"Poly\",0\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"AccRes\",0,0,1,\"eta1_eta1\",\"Poly\",1\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"Poly\",1\)

#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"Poly\",0\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"Poly\",1\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"Poly\",2\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"Poly\",3\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"Poly\",4\)

#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"Raw\",0,0,2,\"eta1_eta1\",\"Poly\",-1\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"RawRes\",0,0,2,\"eta1_eta1\",\"Poly\",-1\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"Poly\",5\)
#
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"Raw\",0,0,1,\"eta1_eta1\",\"Poly\",-1\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"RawRes\",0,0,1,\"eta1_eta1\",\"Poly\",-1\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"AccRes\",0,0,1,\"eta1_eta1\",\"Poly\",5\)
#
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(3,0,\"Raw\",0,0,2,\"eta1_eta1\",\"Poly\",-1\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(3,0,\"RawRes\",0,0,2,\"eta1_eta1\",\"Poly\",-1\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(3,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"Poly\",5\)
#
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(3,0,\"Raw\",0,0,1,\"eta1_eta1\",\"Poly\",-1\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(3,0,\"RawRes\",0,0,1,\"eta1_eta1\",\"Poly\",-1\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(3,0,\"AccRes\",0,0,1,\"eta1_eta1\",\"Poly\",5\)


#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"Poly\",5\)
##root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"Poly\",6\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(4,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"Poly\",7\)

#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(0,0,\"Raw\",0,0,1,\"eta1_eta1\",\"Poly\",-1\)
#root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(0,0,\"Raw\",0,0,2,\"eta1_eta1\",\"Poly\",-1\)
root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(0,0,\"AccRes\",0,0,1,\"eta1_eta1\",\"Poly\",-10\)
root -l -b -q calSysErrorPhiCent_FixedSys_PolySys.C\(0,0,\"AccRes\",0,0,2,\"eta1_eta1\",\"Poly\",-10\)
